---
title: "Jordan V. Lebron"
author: "Xiang Jiang and Albion Shoshi"
date: "April 5, 2024"
output: pdf_document
geometry: left=0.5in,right=0.5in,top=0.5in,bottom=0.5in
urlcolor: blue
---

```{r setupFiles, include = FALSE}
# This template file is based off of a template created by Alex Hayes
# https://github.com/alexpghayes/rmarkdown_homework_template

# Setting Document Options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)
```

```{r}
# Import libraries and data here
library(dplyr)
library(readr)
library(tidyverse)
library(rvest)
```

```{r}
# Downloaded Data from Kaggle
AllStarGamesStats <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/allstar_games_stats.csv')
PerGameStats <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/per_game_stats.csv')
AdancedStat <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/advanced_stats.csv')
Salaries <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/salaries.csv')
AllGameStat <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/allgames_stats.csv')
GameHighStat <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/game_highs_stats.csv')
Totals <- read_csv('/Users/xiangjiang/Documents/GitHub/Stat184Final/totals_stats.csv')
```
```{r}
Data_1 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_2 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
Data_3 <- "https://www.nba.com/stats/leaders?Season=1986-87&SeasonType=Regular+Season"
Data_4 <- "https://www.nba.com/stats/leaders?Season=1987-88&SeasonType=Regular+Season"
Data_5 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_6 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
Data_7 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_8 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
Data_9 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_10 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
Data_11 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_12 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
Data_13 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_14 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
Data_15 <- "https://www.nba.com/stats/leaders?Season=1984-85&SeasonType=Regular+Season"
Data_16 <- "https://www.nba.com/stats/leaders?Season=1985-86&SeasonType=Regular+Season"
```

# Guiding Question: 
* Who is the Greatest Basketball Player of All Time in NBA History, Lebron or Jordan?

# Become acquainted with your data sources:
* Data retrieved from Kaggle.
* 
